Squashed 'src/' changes from 8b11ffe..3fdc799
3fdc799 code formatting
e9bb008 Fixed example
d352aa0 Fixed example
cfb450c Fixed eol write in pattern_formatter_impl
b416685 Fix gcc warning on stat (32 bits)
64c2fe1 Fixed bug in wrapping colors around level name in default pattern
3093271 Fixed example makefile for clang
1dea46e code formatting
4abe403 Update README.md
21d437f Update README.md
84c7f92 Merge pull request #679 from gabime/color-formatting
644c81b Added color ranges to formatter tests
3452892 minor renaming
2f7fdf2 wincolor color formatting support
d040ab9 wincolor color formatting support
c8610d9 support for color formatting
93d41b2 fixed gcc warning about struct stat
c03ae5f Merge branch 'master' of https://github.com/gabime/spdlog
b3988d6 Merge pull request #665 from kasru/more_bench
ad2c7b3 Add README
5e1e897 Remove p7-bench binary
37f2090 Update spdlog-bench
0f66c63 Update easyloggingpp, Add plog
abde900 Merge pull request #663 from kasru/more_bench
fd1c4d7 Fix: unknown conversion specifier 'Y'
70ad1aa Changes: boost, easylogging, g2log, glog, spdlog.
c83dd5d Added: g3log, log4cplus, log4cpp, p7. Changes: boost, easylogging, g2log, glog, spdlog.
18c9968 fixed clang warning about uninitialized values
2008158 Fix clang-tidy warnings about missing braces around if and for statements
7eb6ca6 formatting
5a0f90b clang format namespace fix
2a86cdb Merge branch 'master' of https://github.com/gabime/spdlog
56e4a20 formatting
c739e68 clang format namespace fix
fe8a519 Update logger.h
4445f6f formatting
4ee8987 Changed clang formatting for templates
ea95ea8 Fix potential issue #660
fe5aaf4 Fixed example
5afb5dc Changed clang formatting for templates
f4ce52d Changed clang formatting for templates
1108515 format.sh small fix
8ee7b77 Added -O3 flag to CMakeLists.txt
650daf7 Update common.h
1946818 Update .clang-format
cbe98c0 clang format
ad221b0 Changed function name to level::from_str
a2653d4 clang-format
461b5ef Fixed missing ;
7f1f7b6 Changed function name to level::from_str
d741f1b some clang format fixes
f0606bc Merge branch 'master' of https://github.com/gabime/spdlog
03bc9eb .clang-format
1f79c01 Use clang-format-5.0 instead of astyle
dcf803d Merge pull request #622 from fegomes/to_level
46f9768 change of scope the name_to_level variable
2e09842 added .log extension to bench test
c21dd87 removed class to return size of array.
48c8755 include test to convert functions and change suggested by @gabime
f9750dd Merge branch 'master' into to_level
e8a39c8 Update test_pattern_formatter.cpp
97cdbc4 Merge pull request #653 from tbastos/master
d044369 Fix implicit conversion warnings (-Wsign-conversion)
84d3c90 Fixed g++ 4.9 warnings after the clang-tidy fixes
2e973c8 Merge pull request #647 from DanielChabrowski/clang-tidy
de642b6 astyle applied
5355bd3 readability-named-parameter
35a843f modernize-return-braced-init-list
17caf77 google-build-namespaces
0c94ce0 deleted copy op and a little format
af50d5e readability-inconsistent-declaration-parameter-name
9ce66f2 modernize-pass-by-value
ad62443 google-explicit-constructor
1e1ca23 modernize-use-equals-default
e5bbe57 cppcoreguidelines-pro-type-member
68f9182 performance-unnecessary-value-param
7aed498 modernize-use-default-member-init
d5a3bb5 readability-else-after-return
9ebb9ff readability-implicit-bool-cast
fb6df05 modernize-use-override
7f4c1bb modernize-use-using
abc0d43 astyle
3826ac1 bumped bundled fmt version to 4.1.0
d650fa2 Fixed tests for older gcc compilers
80163dc Better support for WinRT
a8b5bb8 fixed cmake for tests
3620b31 added pattern formatter tests
7709fc7 small fix to pattern_formatter ctor
bce3369 Merge pull request #628 from emadwill/eol
04d0dd5 moved SPDLOG_VERSION macro to common.h
051048e Fixed issue #645 (include tweakme.h from common.h)
7fe3912 astyle
7eb41cc Use -O3 flag in tests
79d55fd Merge branch 'master' of https://github.com/gabime/spdlog
6df52df Use emplace_back in pattern_formatter
bdca50e Fixed issue #637
851b49e Update CMakeLists.txt
e64847b Merge pull request #644 from grzadr/patch-1
8e86172 Fix indentation in line 2916
8cfd71a Merge pull request #635 from DanielChabrowski/cmake_explicit_lang
5d08bd1 Bump example's cmake version to 3.1
646a140 Specify CXX language explicitly in CMake
5eef243 Merge pull request #634 from ColinDuquesnoy/patch-1
11ee683 Fix compilation error with GCC 8
c07e81a Merge pull request #632 from bschindler/wincolor_set_color_public
05b2aab Make set_color public in wincolor_sink to retain configurability
55680db Support for custom EOL per formatter
f4ffddc Merge branch 'master' into to_level
5ab033f Fix issue #629
1dfc828 Merge pull request #624 from yisonPylkita/modern_cmake_tests
f8aec1b Merge branch 'master' of https://github.com/gabime/spdlog.git
51a83da Repplaced map with unordered_map for level->colos mapping
38ccd51 Modern CMake in /tests
8696ad8 new function to convert level_enum from string
c336470 Merge pull request #621 from rcarmich/fix_example_spelling_errors
da51d8d Fixed spelling mistake in example.cpp
22fdd3b Merge pull request #615 from Qix-/master
cae749f clear line after writing log message contents
58e6872 rename grey to black
a59f74e remove needless zeros in reset code
f258af4 Update CMakeLists.txt
ccd675a version 0.16.3
5372d58 comment
751520f Merge pull request #610 from joaomoreno/fix609
357a63d fix spdlog namespace
a938045 use Sleep in Windows instead of sleep_for
32177aa Merge pull request #604 from sam-lunt/improve-macros
ce1df17 Merge pull request #605 from sam-lunt/add-flush-on
9f84133 add global flush_on function
f25f0e0 add (void)0 when logging is disabled
a2890f2 Merge pull request #596 from Broekman/master
de4644b Issue fix for spdlog #595. Conversion warning.
03db102 Update README.md
3d967dd added catch license in tests folder
b53d207 Update file_helper.h
fde1219 Update file_helper.h
4ca6991 astyle
813dcbc version 0.16.2
7663f58 Fixed file_helper::split_by_extenstion tests for gcc
8e3f968 Fixed file_helper::split_by_extenstion and added more tests for it
f695e53 Fixed file_helper::split_by_extenstion and added more tests for it
f257e4e gitignore tests/logs
0ed3e4c Merge branch 'master' of https://github.com/gabime/spdlog
6d355fd report about unknown excepptions before rethrow
dd0b7b2 Merge pull request #590 from fcharlie/master
42e5d98 fix split_by_extenstion parse error extenstion
c060a10 update to version 0.16.1
79a3a63 uupdate version to 0.16.1
52dfd47 Merge pull request #584 from horar/master
48eca46 Merge pull request #586 from horar/fix/warnings
f93277d Solve compiler warning in tests
dda8af0 Update version strings to 0.16.0
ed5498a report unexected exception types
6dd928d Undo fix #529 (causes a warning under gcc and clang when no args passed)
de595fe Fix #529 (SPDLOG_TRACE macro problem)
d460c30 Merge pull request #568 from adubovikov/master
88fe218 Update logger_impl.h
b1be7b9 async log: increased sleep to to 500ms the worker loop
bec6919 added facilty for syslog
2f81ff7 Update README.md
4db70c2 Update README.md
26b390b removed lock from dist_sink::_flush() (moved to base_sink::flush())
a9149c6 added lock on flush in base_sink
859b7f1 fixed test for visual c++
49989e0 fixed test for gcc 4.8 (no regex)
7027492 fixed test comment
f5939f9 astyle
84e3075 Fixed test
3c4a2bf Handle file extensions in rotating and daily loggers
60ce47a Removed include_if.cpp from the tests .sln
613f024 Removed forgotten *_if declarations
799ba2a added SPDLOG_DISABLE_TID_CACHING macro to prevent invalid thread ids after fork
adbc220 enable final keyword by default. Can be disabled in tweakme.h for older compilers
e7cf25a fixed issue #562
dcc7b34 Removed all *_if functions (trace_if, debug_if, info_if,..) because they are redundant and confusing way to preform if
9a8f5c5 Added .idea/ to .gitignore
c41b6d2 astyle
fd170b0 catch(...) exceptions, report it, and rethrow
587b528 Merge pull request #556 from jpcima/syslog-build
36c8e79 Merge pull request #555 from jpcima/windebug-sink
ecec210 accept msvc_sink on all compilers, add name windebug_sink (fixes #554)
76d2620 correct include path for sink/syslog_sink.h
8ca1d84 Removed catch(..) from the codebase. Catch only std::exception
63d7c64 Merge pull request #551 from daylanKifky/modified_includes
10772ea fix wincolor_sink's common.h include
b220bbb fix printf include
5153b44 minor fixes
27e7412 modified path on quoted #includes
93be771 astyle
6ab2f0e Merge pull request #548 from Subenle/master
34a9f24 Declare variables as size_t rather than unsigned.
f70b2ef Fixed cygwin  support
79e97fa Added the license file of the fmtlib in the bundled folder
a66e9bb Minor fix in comment
f5fe681 Fixed issue #546 by adding an "is_empty" method to the queue instead of the buggy approx_size
6fd5f3c Merge pull request #545 from costinm/patch-1
f4f3e3f Use __ANDROID__
23dd8d3 Allow compilation on platforms with unwind (android)
47c17be Merge pull request #457 from rkollataj/appveyor
1f3d939 Merge pull request #538 from berkus/patch-1
fbb8244 Merge pull request #533 from manuel-schiller/patch-1
039b34e rethrow unwind exception
69e6af0 Merge pull request #539 from knowledge4igor/fix_cast_warnings
147bdbf Fix warnings which are caused by C style cast
4974743 Make short month names match in length
1c8cc65 Fix typos
a6b5ef5 Fix typo
cefea32 Fix typos
7f953c1 Merge pull request #535 from vitor-alves/master
20a4143 Update README.md
87a4455 fixed macro tests
21ed318 fixed bug in SPDLOG_TRACE_IF macro and added some related tests
4a159ad Fixed unused variable warning
19264b8 Merge branch 'master' of https://github.com/gabime/spdlog
709948f Fixed issue #527
30d5fd1 Update README.md
9688689 Merge pull request #531 from fogo/printf
e8b7f41 Moved printf include to fmt.h
ee525f9 allow printf style logging
552d621 updated bundled fmt to contain printf
dc8ac4c Update tweakme.h
cd6a8c9 Merge pull request #524 from 2Park/master
375b7fd Fix SPDLOG_WCHAR_TO_UTF8_SUPPORT wchar_t logging
3a21b76 Merge pull request #522 from jasonbeach/feat_add_epoch_formatter
f7fabfb add formatter for unix epoch time in seconds.
a4e6d88 Update README.md
e303f02 Merge pull request #515 from elelel/trace
b242fb0 Compiler-dependent line numbering
02b9f97 Merge pull request #514 from stackforce/feature/improve-cmake-lists
e6b9fa5 cmake: set project version to 0.14.0
fe2fa40 cmake: add some small comments to point out whats being done
ab25004 cmake: add some commend blocks to clearly differentiate CMakeLists file sections
5504630 cmake: improve CMakeLists.txt
c4d93ae Merge pull request #513 from Lectem/patch-1
47cf62f SPDLOG_BUILD_TESTING now depends on BUILD_TESTING
4fba14c Version 0.14.0
cb02b34 Fix issue #510 (spelling)
fced34e bumped fmt version to 4.0.0
268222e Fixed crash in async logger in gcc 4.8.5 regarding static members in pattern_formatter impl
6340c16 Merge pull request #490 from asit-dhal/issue-488
f546036 Merge pull request #502 from gg7/readme-add-gentoo-package
c69b356 readme: Add Gentoo package name
e35c7fd Issue-488: warning for missing enumeration value
5ed4269 Merge pull request #484 from vgabi94/patch-1
3173422 Background color unchanged
fc14ac2 Merge pull request #478 from snapbug/master
13a938f Added TRACE_IF and DEBUG_IF macro definitions when TRACE_ON and DEBUG_ON aren't defined
b75da32 Merge pull request #473 from asit-dhal/master
3a40f0c fixed length and upper case log level tags
4371092 fixed gcc shadow warnings
f06f3f1 Merge pull request #468 from p-alik/master
8fd16fc code formatting (astyle and dos2unix)
9a04e37 Merge pull request #465 from cyres/re_add_color
765095d Add set_color to ansicolor_sink
431fb42 Merge pull request #463 from sheldonlyr/threadid-osx
66a2c49 More meaningful thread id for OSX
1e4f14c Update README.md
c0f0fd7 Merge pull request #460 from asit-dhal/master
97be453 trace_if and debug_if macro added
868c0ce Update README file
a767f07 Conditional logging in the example
de0154c Test Case for conditional logging
380233b mend
b463b06 conditional logging for all levels
9a189ba conditional logging implementation
ed7c3a8 conditional logging implementation
d3e013a Merge pull request #459 from cneumann/create_async
8ee90d3 Add create_async factory functions for async loggers
e6cbc22 Merge pull request #456 from rkollataj/mingw_fix
2e84ca4 Adding additional build environments for AppVeyor
fab55c8 Fix for MinGW error: 'There are no arguments that depend on a template parameter'
9470bdd Update common.h
5d5f2f3 Merge pull request #451 from ThePhD/pattern_time
7e09f01 brace styling
d98d548 use if statement instead of switch (changes of adding new time specifications outside of standard are probably unlikely anyhow) pattern_time -> pattern_time_type ptime variable name -> pattern_time variable name make sure four spaces used, not tabs
18a0455 _pattern was never set... but it was also never used. Intentional by @gabime, or a reflection of a refactor with some data member left behind?
5c5080d implement a flag (in this case, an enumeration) that allows control over the type; we make it an enum for possible expansions of time abstractions that might make it into the C++ standard in the future (see Howard Hinnant's date/timezone library) or might be usefully-available from the OS at some point in time
13fb255 Fixed issue #449
c6ad598 Merge pull request #450 from stonedreamforest/master
f8d509d Fixed issues 449
e1d4c46 Minor formatting
8d164f4 tweakme disable counters by default
42a56f6 fixed "final" keyword error
d56fa23 fixed compilation errors
095cb1f Added _flush() to base_sink
e215758 Update ansicolor_sink.h
87f5a60 Update ansicolor_sink.h
3613449 Refactored message counter a little
7da3e47 fixed color comment
1f9f9c0 fixed flush
8c240fa changed info color to regular insted of bold
7bbab68 use data() istead of c_str() in ansicolor_sink
6cc7e73 astyle
40fc5be fixed compilation
3899e8a fixed compilation warning
7f84daf fixed compilation
98addad Disable colors if terminal no attached and simplfy ansicolor_sink
1ab63ff Merge pull request #445 from alzix/message_counter
ef6eb37 disable message counter feature in tweakme.h
f29ff77 implement message counter feature
bf3a415 Merge pull request #447 from eliaskosunen/master
c6c5a46 Fix OSX builds of details/os.h
def86e6 Fixed forgotten inline keyword
1d6842f bugfix in color detection and astyle
eb92cc3 Merge branch 'master' of https://github.com/gabime/spdlog.git
bd25f59 Don't use color escape codes if terminal doesn't support them in ansicolor_sink
a39f71d Merge pull request #444 from alzix/minor-fixes
8329d97 fix indentation
57dc877 Merge pull request #443 from alzix/revert-411
6547675 Revert "Merge pull request #441 from alzix/count_discarded"
1319903 Update tweakme.h
0387333 Merge pull request #441 from alzix/count_discarded
2b008ef disable SPDLOG_ASYNC_COUNT_DISCARDED_MSG
0f25b25 add async_logger tests
42258a1 move discarded message handling to a dedicated function
862d2f6 Merge pull request #442 from sidyhe/feature
0aeaf9e add an option to warn about discarded messages
8ee6d38 add wide string to utf8 string support
47006c4 Merge pull request #436 from bahostetterlewis/master
84a4f56 Allow compiler to select an strerror_r stringify
e9b8286 Merge branch 'master' of https://github.com/gabime/spdlog.git
81965bc Fixed some analyzer warnings
52292fb Update android_sink.h
6927aa1 Update android_sink.h
f0f4a52 Merge pull request #427 from alzix/android_sink_retry
2f205a6 android sink - add retry mechanism
4a25802 Update README.md
260a745 Merge pull request #425 from jcelerier/feature/final_qualifier
4da5fa2 add SPDLOG_FINAL information in tweakme.h
53138c2 Add an optional final qualifier to types
9e6d81d Merge pull request #422 from theamirocohen/android_log
45e3e70 Android_logger apply its own formatting to every print by adding timestamps, severity, thread and process ids, thus the option flag in the ctor

git-subtree-dir: src
git-subtree-split: 3fdc7996db80019074b0753fee589de2260e5d76