Squashed 'src/' changes from 703a1d9..8b11ffe
8b11ffe Merge pull request #413 from odeits/patch-3
0c89bea Merge pull request #415 from odeits/patch-5
d35e229 Merge pull request #414 from odeits/patch-4
0a70ef8 Merge pull request #412 from odeits/patch-2
6670d3b fix typos in base_sink.h
82404f6 fix typo potentialy to potentially
8d5ecc1 Fix typo immediatly immediately
682d2e0 Fix typo in comment Unkown to Unknown
15af514 Update file_helper.h
129781f Merge pull request #408 from odeits/patch-1
b9e8fd2 Merge pull request #407 from eliaskosunen/master
ea35925 Fix typo Unkown to Unknown
a3e84cb Update example in README.md
51b3cc0 Merge pull request #405 from o-mdr/master
d315bba Initialising members via constructor
b5d838c - Reverting changes to mpmc queue
6a41bc4 [#404] Reading past valid address with multisink logger
b638c71 [#404] Reading past valid address with multisink logger
2b5c361 Update async_log_helper.h
f85a086 version 0.13.0
0c276be astyle
5a8cecd fix unused warning message
397d486 Fixed issue #396 and added some tests to catch it
27df6eb Merge pull request #403 from Falconne/master
ad1c187 Disambiguate fmt logging methods that are using variadic templates.
029e6ed Merge pull request #399 from devanshdalal/patch-1
a55615c Update README.md
e8da69e Merge pull request #394 from zamaudio/spdlog-updatefmt-3.0.1
8192c13 fmt: update bundled fmt to 3.0.1 (7fa8f8f)
270c08b Merge pull request #377 from tekezo/master
a4714a6 use double-braces in std::array initialization
5585299 Merge pull request #375 from horar/master
fd8df5b Don't hardcode '.txt.' log file name suffix (resolve #333)
d7a8db8 Update README.md
93d84e5 v0.12.0
3119378 Merge pull request #370 from jcelerier/fix/remove_static_global_strings
ef665e9 Don't deduce return types for days / months
20f4428 Update README.md
b65c7ba Update README.md
06b8193 Add missing consts
a626ebb Replace static global std::string arrays by Meyer singletons. This improves thread-safety.
054eb55 Moved `SPDLOG_VERSION` macro to spdlog.h
4f50c5d Update spdlog.h
7481a8e Update common.h
a76a5cf Update README.md
904bed9 Added SPDLOG_VERSION macro to common.h
8650c15 Updated install options section
35865ee Merge pull request #348 from w0land/cmake_prefix
50c181e Add prefix for BUILD_TESTING cmake option
2ec1880 Update README.md
e7ec922 Update async_log_helper.h
3845611 Update null_sink.h
0a3a3f0 Updated comment on thread safety
58853d9 Update README.md
5ee1490 Update README.md
2d87378 astyle
fec467d extra blank line between comments
b5f34c5 typo in comment
92db811 option to  prevent child processes from inheriting log file desciptors (#define SPDLOG_PREVENT_CHILD_FD)
af35f9c Merge pull request #330 from PMExtra/master
0e01688 Update os.h
b1a55ca Use the feature checking macros to detect thread_local support in clang.
68cc3e6 Merge pull request #329 from PMExtra/master
f7574eb fixed compilation error in clang before version 8 (does not support thread_local keyword)
3349404 fixed compilation error in 2013 (does not support thread_local keyword)
5d23e88 astyle
6d8efa8 store thread_id in tls
343904b add missing include to widnows _getpid
cf73f02 pid support (added the %P option to formatter)
cda27d2 Merge pull request #322 from onnodb/FixIssue321
b61be73 Fix compilation errors in "wincolor_sink.h"
b2ce646 Merge pull request #319 from jktjkt/cmake
f058d3a cmake: use -Wall on GCC and Clang
1c31800 cmake: Use a standard option for controlling the tests
61cdd17 cmake: List spdlog's content in IDEs
d6b34d7 Updated to fmt version 796beaaddb5226162fe00c2c55e322d80d26f3d8
bd6fe56 astyle previous commits
d142f13 Updated fmto to version def687462c32ec40757e49eb6069f109d50236d6
e12916c Fixed issue #317 (Build error on raspberry pi)
f6cece2 Merge
817371b Fix issue #317 (Build error on raspberry pi)
9eee823 Fix issue #315
4e768c1 Merge pull request #314 from osx2000/master
3cd497e extended conditional compilation to __SUNPRO_CC
e9fc4ac Fully qualified std::this_thread::yield()
9ccb6af Merge pull request #305 from chenhayat/vs2013_fix
5259b3d Fix Klockwork compilation warning
8c67d6e Merge pull request #304 from chenhayat/vs2013_fix
b4cb1fe removed external library changes
0c16b9a Remove casting from previous commit and fix the following Klockwork issues:
83d192b Fix compilation error C2664  on VS2013
87ddb9a astyle
6128a87 Fix issue #300
6987838 Fixed vc warning on x64 build
f14d1c0 astyle
0cfdad4 Windows console color support. Replaced color param in API  with new functions
94dbefe Merge pull request #296 from guoxiao/fix
73e53c7 Remove extra ';'
9b218d4 Convert off_t to size_t
541dd88 Update common.h
ca928bc Fix issue #295
b642482 removed empty line

git-subtree-dir: src
git-subtree-split: 8b11ffe16356909db7ef516a582b853964b4c572